### ISSUE TITLE
RDS RadioText string should scroll during playback

### ISSUE THREAD

**Issue by djp952** [djp952/pvr.rtlradio#10]
I need to look into what's possible here.  The RDS RadioText string will scroll in the "RDS" dialog if it's longer than the UI allows for, but the request is to have it do that during normal playback.

The RDS implementation in Kodi appears to have been somewhat abandoned as of Kodi 18 "Leia", but it may be possible to keep two copies of the RadioText string in the PVR addon and make it scroll by manipulating the character order and sending Kodi new RadioText packets more frequently.  I think this would have a bad side-effect with the "RDS" dialog, but will have to see.

This one feels like a PR for Kodi rather than an addon change.

**Comment by ksooo** [comment]
You should open an issue/PR for Kodi for that.

**Comment by djp952** [comment]
Scrolling the text by manipulating it in the addon would break support for RadioText+ so it fundamentally shouldn't/can't be done.  RadioText+ sends the character position and length of data elements in the RadioText, they are tied together.  I don't think the vision for RDS in Kodi was to have this scroll, but if the user raises the concern again I'll look from the Kodi perspective.
