### ISSUE TITLE
Run greyed out in Kodi

### ISSUE THREAD

**Issue by boxcar32** [djp952/pvr.rtlradio#34]
Hi,

Thanks for the time and effort on this. I have the RTL-SDR Blog R820T2 RTL2832U but after installing the zip addon in matrix (windows 10) run is greyed out. Can you point me in the right direction? I am able to play FM via SDRSharp. I'm also about to test on raspberry pi 400.

Thanks,

**Comment by djp952** [comment]
Hi!  Welcome!  Sorry for not devoting much (any) time to this yet this year.  Many deficiencies to work on still :)

Can you post a screen shot of what you're seeing? I am unaware of any "Run" command that's associated with a PVR in Kodi?  The way it works is that you install the addon and then import channels (you can also add channels via the PVR Channel Manager, but the interface I made isn't too good): https://github.com/djp952/pvr.rtlradio/blob/main/doc/importexport.md

You then go into the "Radio" area of Kodi and should see the channels there like you would for TV.

On Windows, if you're already done the zadig stuff (sounds like you did), that really should be all that you need to do, install, add channels, go.  

I realize the documentation I have is mostly garbage, hard to find time to concentrate on this :)

**Comment by boxcar32** [comment]
[](url
![Screenshot 2022-03-06 204501](https://user-images.githubusercontent.com/100957648/156959017-6613c375-2690-4ec7-a595-f5f5636be7fd.png)
)

**Comment by boxcar32** [comment]
Thanks got it to work.

**Comment by djp952** [comment]
Cool!  I promise to work on documentation at some point.  Run is for different kinds of addons :)

Marking as closed, but please feel free to open new ones!  Not really "active" on this right now, but will do what I can to help out!
